from pathlib import Path

from reconforge.models.target import Target
from reconforge.utils.logger import Logger


class HTMLExporter:
    """
    Export scan results to a standalone HTML report.
    """

    @staticmethod
    def export(target: Target, output_file: str) -> None:

        html = HTMLExporter.build_html(target)

        path = Path(output_file)
        path.parent.mkdir(parents=True, exist_ok=True)

        path.write_text(html, encoding="utf-8")

        Logger.success(f"HTML report saved to {path}")

    @staticmethod
    def build_html(target: Target) -> str:

        sections = [
            HTMLExporter.render_target(target),
            HTMLExporter.render_findings(target),
            HTMLExporter.render_dns(target),
            HTMLExporter.render_http(target),
            HTMLExporter.render_tls(target),
            HTMLExporter.render_whois(target),
            HTMLExporter.render_technology(target),
            HTMLExporter.render_ports(target),
        ]

        return f"""<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>ReconForge Report</title>

<style>

body {{
    margin: 0;
    padding: 40px;
    background: #eef2f7;
    color: #1f2937;
    font-family: "Segoe UI", Arial, sans-serif;
}}

.container {{
    max-width: 1200px;
    margin: auto;
}}

.header {{
    background: linear-gradient(135deg, #1565C0, #1E88E5);
    color: white;
    padding: 30px;
    border-radius: 14px;
    box-shadow: 0 8px 20px rgba(0,0,0,0.15);
    margin-bottom: 35px;
}}

.header h1 {{
    margin: 0;
    font-size: 36px;
}}

.header p {{
    margin-top: 10px;
    opacity: 0.9;
}}

.dashboard {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 20px;
    margin-bottom: 30px;
}}

.card {{
    background: white;
    border-radius: 12px;
    padding: 20px;
    text-align: center;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
}}

.card h3 {{
    margin: 0;
    color: #1565C0;
    font-size: 16px;
}}

.card p {{
    margin: 12px 0 0;
    font-size: 30px;
    font-weight: bold;
}}

.section {{
    background: white;
    border-radius: 12px;
    padding: 24px;
    margin-bottom: 30px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
}}

.section h2 {{
    margin-top: 0;
    color: #1565C0;
    border-bottom: 2px solid #e5e7eb;
    padding-bottom: 10px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

th {{
    background: #1565C0;
    color: white;
    text-align: left;
    padding: 12px;
}}

td {{
    padding: 12px;
    border-bottom: 1px solid #e5e7eb;
    vertical-align: top;
}}

tr:nth-child(even) {{
    background: #f8fafc;
}}

.footer {{
    margin-top: 40px;
    text-align: center;
    color: #6b7280;
    font-size: 14px;
}}
.badge {{
    display: inline-block;
    padding: 6px 12px;
    border-radius: 999px;
    color: white;
    font-size: 13px;
    font-weight: bold;
}}

.badge-info {{
    background: #1976D2;
}}

.badge-low {{
    background: #F9A825;
}}

.badge-medium {{
    background: #D32F2F;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>ReconForge Report</h1>

<p>
Target:
<strong>{target.original}</strong><br>
Generated by ReconForge
</p>

</div>
{HTMLExporter.render_dashboard(target)}
{"".join(sections)}

</div>

</body>

</html>
"""

    @staticmethod
    def render_target(target: Target) -> str:
        """
        Render the target information section.
        """

        return HTMLExporter.render_key_value_section(
            "Target Information",
            [
                ("Original", target.original),
                ("Hostname", target.hostname),
                ("Type", target.target_type),
                ("Scheme", target.scheme),
                ("Port", target.port),
            ],
        )

    @staticmethod
    def render_findings(target: Target) -> str:
        """
        Render assessment findings.
        """

        findings = target.results.findings

        if not findings:
            return ""

        rows = []

        for finding in findings:
            rows.append(
                f"""
<tr>
<td>{HTMLExporter.severity_badge(finding.severity.value)}</td>
<td>{finding.title}</td>
<td>{finding.description}</td>
<td>{finding.recommendation}</td>
</tr>
"""
            )

        return f"""
<div class="section">

<h2>Assessment Findings</h2>

<table>

<tr>
<th>Severity</th>
<th>Title</th>
<th>Description</th>
<th>Recommendation</th>
</tr>

{''.join(rows)}

</table>

</div>
"""

    @staticmethod
    def render_dns(target: Target) -> str:
        """
        Render the DNS information section.
        """

        dns = target.results.dns

        if dns is None:
            return ""

        return HTMLExporter.render_key_value_section(
            "DNS Information",
            [
                ("A Records", dns.a_records),
                ("AAAA Records", dns.aaaa_records),
                ("MX Records", dns.mx_records),
                ("NS Records", dns.ns_records),
                ("TXT Records", dns.txt_records),
                ("CNAME", dns.cname),
            ],
        )

    @staticmethod
    def render_http(target: Target) -> str:
        """
        Render the HTTP information section.
        """

        http = target.results.http

        if http is None:
            return ""

        return HTMLExporter.render_key_value_section(
            "HTTP Information",
            [
                ("Status Code", http.status_code),
                ("Server", http.server),
                ("Content Type", http.content_type),
                ("Content Length", http.content_length),
                ("Redirect URL", http.redirect_url),
                ("Title", http.title),
                ("Response Time", f"{http.response_time:.2f} ms" if http.response_time else "-"),
            ],
        )

    @staticmethod
    def render_tls(target: Target) -> str:
        """
        Render the TLS information section.
        """

        tls = target.results.tls

        if tls is None:
            return ""

        return HTMLExporter.render_key_value_section(
            "TLS Information",
            [
                ("Subject", tls.subject),
                ("Issuer", tls.issuer),
                ("SANs", tls.sans),
                ("Valid From", tls.valid_from),
                ("Valid Until", tls.valid_until),
                ("Days Remaining", tls.days_remaining),
                ("TLS Version", tls.tls_version),
                ("Cipher", tls.cipher),
            ],
        )

    @staticmethod
    def render_whois(target: Target) -> str:
        """
        Render the WHOIS information section.
        """

        whois = target.results.whois

        if whois is None:
            return ""

        return HTMLExporter.render_key_value_section(
            "WHOIS Information",
            [
                ("Registrar", whois.registrar),
                ("Creation Date", whois.creation_date),
                ("Expiration Date", whois.expiration_date),
                ("Updated Date", whois.updated_date),
                ("Name Servers", whois.name_servers),
            ],
        )

    @staticmethod
    def render_technology(target: Target) -> str:
        """
        Render the detected technologies section.
        """

        technology = target.results.technology

        if technology is None:
            return ""

        return HTMLExporter.render_key_value_section(
            "Technology Information",
            [
                ("Technologies", technology.technologies),
            ],
        )

    @staticmethod
    def render_ports(target: Target) -> str:
        """
        Render the port scan section.
        """

        ports = target.results.ports

        if ports is None:
            return ""

        rows = []

        for port in ports.open_ports:
            banner = port.banner if port.banner else "-"

            rows.append(
                f"""
<tr>
<td>{port.port}</td>
<td>{port.service}</td>
<td>{banner}</td>
</tr>
"""
            )

        if not rows:
            rows.append(
                """
<tr>
<td colspan="3">No open ports detected.</td>
</tr>
"""
            )

        return f"""
<div class="section">
<h2>Port Scan</h2>

<table>

<tr>
<th>Port</th>
<th>Service</th>
<th>Banner</th>
</tr>

{''.join(rows)}

</table>
</div>
"""

    @staticmethod
    def table_row(field: str, value: object) -> str:

        if value is None:
            value = "-"

        elif isinstance(value, list):
            value = ", ".join(str(v) for v in value) if value else "-"

        return f"""
<tr>
<td>{field}</td>
<td>{value}</td>
</tr>
"""

    @staticmethod
    def severity_badge(severity: str) -> str:
        """
        Render a coloured severity badge.
        """

        css = {
            "INFO": "badge-info",
            "LOW": "badge-low",
            "MEDIUM": "badge-medium",
        }.get(severity, "badge-info")

        return f'<span class="badge {css}">{severity}</span>'

    @staticmethod
    def render_key_value_section(
        title: str,
        rows: list[tuple[str, object]],
    ) -> str:
        """
        Render a standard two-column key/value section.
        """

        return HTMLExporter.section(
            title,
            [
                HTMLExporter.table_row(field, value)
                for field, value in rows
            ],
        )

    @staticmethod
    def render_dashboard(target: Target) -> str:

        http_status = "-"
        if target.results.http:
            http_status = target.results.http.status_code

        open_ports = 0
        if target.results.ports:
            open_ports = len(target.results.ports.open_ports)

        technologies = 0
        if target.results.technology:
            technologies = len(target.results.technology.technologies)

        a_records = 0
        if target.results.dns:
            a_records = len(target.results.dns.a_records)

        return f"""
<div class="dashboard">

<div class="card">
<h3>HTTP Status</h3>
<p>{http_status}</p>
</div>

<div class="card">
<h3>Open Ports</h3>
<p>{open_ports}</p>
</div>

<div class="card">
<h3>Technologies</h3>
<p>{technologies}</p>
</div>

<div class="card">
<h3>A Records</h3>
<p>{a_records}</p>
</div>

</div>
"""

    @staticmethod
    def section(title: str, rows: list[str]) -> str:

        return f"""
<div class="section">
<h2>{title}</h2>

<table>

<tr>
<th>Field</th>
<th>Value</th>
</tr>

{''.join(rows)}

</table>
</div>
"""